### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by Liberasys** [jczic/MicroDNSSrv#1]
Hello JC, can you put a license header in your code please ?

**Comment by jczic** [comment]
Hello,
Yes okay no problem, I'll make that this afternoon :)
Thank you for your integration :')
If you want, I've too in my github a cool WebClient and RESTClient more efficient than urequest...

**Comment by jczic** [comment]
I've added the license.

**Comment by Liberasys** [comment]
Thank you :-)
