### ISSUE TITLE
Thread not started with Loboris firmware

### ISSUE THREAD

**Issue by Liberasys** [jczic/MicroDNSSrv#2]
Due to Loboris thread implementation, a thread name is required at start.
ex : start_new_thread("MicroDNSSrv", func, args)
A solution could be to detect Loboris firmware in the code (version='ESP32_LoBo_v3.1.14 on 2017-01-29')...

I have seen your JSON/RPC client, I think I will test it someday :-)

BR Gautier
(JC : je mets mes remarques sur git, cela peut servir à d'autres).

**Comment by jczic** [comment]
Okay, threads are now normally compatible with Loboris.
This is also ok for MicroWebSrv.
